// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDNyfSbiFY4kfOCuLo5OBwnNF7Lg7RvhA',
    appId: '1:1024447885857:web:d667ad80f88f12bab62960',
    messagingSenderId: '1024447885857',
    projectId: 'notes-f96eb',
    authDomain: 'notes-f96eb.firebaseapp.com',
    storageBucket: 'notes-f96eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC746z9zxJUJ7oVxxwwUfmMJFXOlJTmtoA',
    appId: '1:1024447885857:android:d981ce7852fbc683b62960',
    messagingSenderId: '1024447885857',
    projectId: 'notes-f96eb',
    storageBucket: 'notes-f96eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHydvk7oly0UFKTSU3SPNLKxZht8YSlW0',
    appId: '1:1024447885857:ios:d94af9f1d7ccb28fb62960',
    messagingSenderId: '1024447885857',
    projectId: 'notes-f96eb',
    storageBucket: 'notes-f96eb.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHydvk7oly0UFKTSU3SPNLKxZht8YSlW0',
    appId: '1:1024447885857:ios:d94af9f1d7ccb28fb62960',
    messagingSenderId: '1024447885857',
    projectId: 'notes-f96eb',
    storageBucket: 'notes-f96eb.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDNyfSbiFY4kfOCuLo5OBwnNF7Lg7RvhA',
    appId: '1:1024447885857:web:f97110f691a1d857b62960',
    messagingSenderId: '1024447885857',
    projectId: 'notes-f96eb',
    authDomain: 'notes-f96eb.firebaseapp.com',
    storageBucket: 'notes-f96eb.firebasestorage.app',
  );
}
