// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrP62PfEVV4KNHgkgx40EqrDx9kBfv0zU',
    appId: '1:635923203074:web:31962015fa27b7ccd7131b',
    messagingSenderId: '635923203074',
    projectId: 'mdpgold',
    authDomain: 'mdpgold.firebaseapp.com',
    storageBucket: 'mdpgold.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0jCch8Bn_miz9eF7dZBWc58ZoZjJiOhw',
    appId: '1:635923203074:android:bfa09b7cf939022dd7131b',
    messagingSenderId: '635923203074',
    projectId: 'mdpgold',
    storageBucket: 'mdpgold.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0O7hBI6sEFRStdTJrcHJvSr2R2yFYLRU',
    appId: '1:635923203074:ios:ec13d8329e68047bd7131b',
    messagingSenderId: '635923203074',
    projectId: 'mdpgold',
    storageBucket: 'mdpgold.firebasestorage.app',
    iosBundleId: 'com.example.mdpgold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0O7hBI6sEFRStdTJrcHJvSr2R2yFYLRU',
    appId: '1:635923203074:ios:ec13d8329e68047bd7131b',
    messagingSenderId: '635923203074',
    projectId: 'mdpgold',
    storageBucket: 'mdpgold.firebasestorage.app',
    iosBundleId: 'com.example.mdpgold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrP62PfEVV4KNHgkgx40EqrDx9kBfv0zU',
    appId: '1:635923203074:web:ed273ec9056fd7e6d7131b',
    messagingSenderId: '635923203074',
    projectId: 'mdpgold',
    authDomain: 'mdpgold.firebaseapp.com',
    storageBucket: 'mdpgold.firebasestorage.app',
  );
}
