// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6mnzYP_Vnr5_La3QmCIoGal9E1OYlAvo',
    appId: '1:796602268042:web:bdac81576e72ea7449b073',
    messagingSenderId: '796602268042',
    projectId: 'daftar-belanja-152ff',
    authDomain: 'daftar-belanja-152ff.firebaseapp.com',
    databaseURL: 'https://daftar-belanja-152ff-default-rtdb.firebaseio.com',
    storageBucket: 'daftar-belanja-152ff.firebasestorage.app',
    measurementId: 'G-B3ZSCWLHGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGjEyMsFQtwdC1CwOX-BcFRtyFSpCiE9o',
    appId: '1:796602268042:android:36ee4ea327825f5849b073',
    messagingSenderId: '796602268042',
    projectId: 'daftar-belanja-152ff',
    databaseURL: 'https://daftar-belanja-152ff-default-rtdb.firebaseio.com',
    storageBucket: 'daftar-belanja-152ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-xzRvIjK_P6xRbJuVq9H6iOR8mJ38vCI',
    appId: '1:796602268042:ios:278e74a52002ff0949b073',
    messagingSenderId: '796602268042',
    projectId: 'daftar-belanja-152ff',
    databaseURL: 'https://daftar-belanja-152ff-default-rtdb.firebaseio.com',
    storageBucket: 'daftar-belanja-152ff.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-xzRvIjK_P6xRbJuVq9H6iOR8mJ38vCI',
    appId: '1:796602268042:ios:278e74a52002ff0949b073',
    messagingSenderId: '796602268042',
    projectId: 'daftar-belanja-152ff',
    databaseURL: 'https://daftar-belanja-152ff-default-rtdb.firebaseio.com',
    storageBucket: 'daftar-belanja-152ff.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6mnzYP_Vnr5_La3QmCIoGal9E1OYlAvo',
    appId: '1:796602268042:web:0f7f07b825793e5349b073',
    messagingSenderId: '796602268042',
    projectId: 'daftar-belanja-152ff',
    authDomain: 'daftar-belanja-152ff.firebaseapp.com',
    databaseURL: 'https://daftar-belanja-152ff-default-rtdb.firebaseio.com',
    storageBucket: 'daftar-belanja-152ff.firebasestorage.app',
    measurementId: 'G-QZNR5M31N2',
  );
}
